### PR TITLE
Changed unpack to table.unpack on line 85

### PR DESCRIPTION
**Pull request by foeb**

### CODE REVIEW

**Comment by tesselode** [comment]
The better solution would be to put at the top:
`local unpack = unpack or table.unpack`
This gives you compatibility with Lua 5.1 and 5.2.

**Comment by foeb** [comment]
That would be great too. I'm new to Lua and I wasn't aware of that difference between the versions.

**Comment by tesselode** [comment]
I assume you were trying to use this with Lua 5.3 and it wasn't working?

**Comment by foeb** [comment]
Yeah. It complained about unpack being nil, so I thought it was a typo that somehow passed through the cracks.

**Comment by tesselode** [comment]
I don't blame you for not knowing, I only learned that `unpack` got renamed to `table.unpack` pretty recently. I'm sure the change is fine, I'll just check it really quick tomorrow.

**Pull request merged**
